
services:
  api:
    build:
      context: api
    environment:
      - POC_API_KEY=${POC_API_KEY:-abc123}
      - POC_API_PORT=${POC_API_PORT:-8000}
      - POC_API_LOG_LEVEL=${POC_API_LOG_LEVEL:-info}
      - POC_DB_PORT=${POC_DB_PORT:-5432}
      - PYTHONUNBUFFERED=1
    ports:
      - "${POC_API_PORT:-8000}:${POC_API_PORT:-8000}"
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poc
      POC_DB_PORT: ${POC_DB_PORT:-5432}
    ports:
      - "${POC_DB_PORT:-5432}:${POC_DB_PORT:-5432}"
    command: -p ${POC_DB_PORT:-5432}
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
