
services:
  database:
    build: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-dvdrental}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    environment:
      API_PORT: ${API_PORT:-8000}
      API_LOG_LEVEL: ${API_LOG_LEVEL:-info}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-dvdrental}
    ports:
      - '${API_PORT:-8000}:8000'

volumes:
  pgdata:
