name: Lint API service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  ruff:
    name: Run ruff code formatter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "api/.python-version"

      - name: Install the project
        run: uv sync --only-dev --directory api

      - name: Run Ruff Check
        run: uvx --directory api ruff check .

