name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Run unit and integration tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install the  project
        run: uv sync --all-extras --dev

      - name: "Run unit tests"
        run: uv run pytest tests/test_unit.py

      - name: "Run integration tests"
        run: uv run pytest tests/test_integration.py

